services:
  - type: web
    name: django-site
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
